name: 'FTP Interactions'
description: 'GitHub Action to copy/delete files over FTP (based on https://github.com/cinderblockgames/ftp-action)'
branding:
  icon: arrow-up-circle
  color: white
inputs:
  host:
    description:
      'Address for the FTP host.'
    required: true
  port:
    description:
      'Port for the FTP host.'
    required: false
    default: '21'
  username:
    description:
      'Username for the FTP host.'
    required: true
  password:
    description:
      'Password for the FTP host.'
    required: true
  localDir:
    description:
      'Local directory from which to upload.'
    required: false
    default: '/'
  ftpAction:
    description:
      'FTP Action: None | Copy | DeleteAppOfflineHtm.'
    required: true
    default: 'None'
  ignoreCertificateErrors:
    description:
      'Ignore certificate errors.'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--host'
  - ${{ inputs.host }}
  - '--port'
  - ${{ inputs.port }}
  - '--username'
  - ${{ inputs.username }}
  - '--password'
  - ${{ inputs.password }}
  - '--localDir'
  - ${{ inputs.localDir }}
  - '--ftpAction'
  - ${{ inputs.ftpAction }}
  - '--ignoreCertificateErrors'
  - ${{ inputs.ignoreCertificateErrors }}
  